/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fff9ed",
        "surface-container-low": "#fcf3d8",
        "on-tertiary": "#ffffff",
        "surface-tint": "#7a5907",
        "on-tertiary-fixed": "#1b1c1c",
        "on-primary": "#ffffff",
        "background": "#fff9ed",
        "error": "#ba1a1a",
        "tertiary-fixed": "#e4e2e2",
        "secondary-fixed-dim": "#e7bdb1",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-tertiary-fixed-variant": "#464747",
        "on-secondary-fixed-variant": "#5d4037",
        "inverse-on-surface": "#faf0d5",
        "primary": "#7a5907",
        "secondary": "#77574d",
        "surface": "#fff9ed",
        "outline-variant": "#d2c5b2",
        "on-secondary-container": "#795950",
        "on-surface-variant": "#4e4638",
        "tertiary-container": "#a09f9f",
        "surface-container-highest": "#ebe2c8",
        "secondary-container": "#fed3c7",
        "on-secondary-fixed": "#2c160e",
        "surface-variant": "#ebe2c8",
        "surface-dim": "#e2dabf",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1f1c0b",
        "on-primary-fixed-variant": "#5d4200",
        "on-primary-fixed": "#261900",
        "inverse-primary": "#edc06a",
        "primary-container": "#c29947",
        "outline": "#807666",
        "on-error": "#ffffff",
        "tertiary": "#5e5e5e",
        "inverse-surface": "#35301e",
        "primary-fixed": "#ffdea5",
        "on-tertiary-container": "#363637",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#edc06a",
        "on-background": "#1f1c0b",
        "surface-container": "#f7eed2",
        "surface-container-high": "#f1e8cd",
        "on-error-container": "#93000a",
        "on-primary-container": "#483200"
      },
      fontFamily: {
        "headline": ["'Pixelify Sans'", "sans-serif"],
        "body": ["'Pixelify Sans'", "sans-serif"],
        "label": ["'Pixelify Sans'", "sans-serif"],
        "serif": ["'Pixelify Sans'", "sans-serif"],
        "sans": ["'Pixelify Sans'", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
